### ISSUE TITLE
Doesn't throw error when 'undefined' language is set

### ISSUE THREAD

**Issue by BolverBlitz** [YouTwitFace/new-i18n#4]
I accidentally made a mistake:

```js
config.language = 'DE' //(My mistake) Should be 0
msg = msg + i18n(i18n.languages[config.language], "R" + f.getRandomInt(1)+1)
console.log(msg);
```

Log:
R2

Should log value of R2

I expect an error or exception at this point in my Log.

**Comment by YouTwitFace** [comment]
This was intentional. I'm not sure why I chose this approach and I'm willing to change it, but it will be a breaking change.

**Comment by BolverBlitz** [comment]
Breaking change means?

**Comment by YouTwitFace** [comment]
@BolverBlitz a breaking change is when there is a change in the way a library works that will cause projects using that library to break.

**Comment by BolverBlitz** [comment]
Ok, well then lets close this issure without "fixing" because i´m very lazy
